import { Page, View, Text, Image } from "@react-pdf/renderer";
import { styles, colors } from "./styles";

interface CoverPageProps {
  garmentType: string;
  imageUrl?: string;
  difficulty: string;
  estimatedTime: string;
  size: string;
  createdAt: string;
  language: "fr" | "en";
}

export function CoverPage({
  garmentType,
  imageUrl,
  difficulty,
  estimatedTime,
  size,
  createdAt,
  language,
}: CoverPageProps) {
  const texts = {
    fr: {
      tagline: "your French knitting studio",
      subtitle: "Patron sur-mesure généré par La Maille",
      sizeLabel: "Taille",
      welcome: "Bienvenue dans votre atelier numérique. Ce patron a été créé spécialement pour vous, à partir de votre photo et de vos mesures. Prenez le temps de lire les instructions, faites confiance à vos mains, et surtout... profitez du voyage.",
      team: "L'équipe La Maille",
      createdOn: "Créé le",
    },
    en: {
      tagline: "your French knitting studio",
      subtitle: "Custom pattern generated by La Maille",
      sizeLabel: "Size",
      welcome: "Welcome to your digital workshop. This pattern was created especially for you, from your photo and measurements. Take time to read the instructions, trust your hands, and above all... enjoy the journey.",
      team: "The La Maille team",
      createdOn: "Created on",
    },
  };
  const t = texts[language];
  return (
    <Page size="A4" style={[styles.page, { padding: 0 }]}>
      {/* Image principale - 50% de la page */}
      {imageUrl && (
        <View style={{ height: "45%", overflow: "hidden" }}>
          <Image
            src={imageUrl}
            style={{
              width: "100%",
              height: "100%",
              objectFit: "cover",
            }}
          />
        </View>
      )}

      {/* Contenu */}
      <View style={{ padding: 40, flex: 1 }}>
        {/* Logo texte */}
        <View style={{ marginBottom: 24 }}>
          <Text style={{ fontSize: 24, fontWeight: "bold", letterSpacing: 2 }}>
            LA MAILLE
          </Text>
          <Text style={{ fontSize: 9, color: colors.muted }}>
            {t.tagline}
          </Text>
        </View>

        {/* Titre */}
        <Text style={[styles.h1, { fontSize: 32, marginBottom: 4 }]}>
          {garmentType}
        </Text>
        <Text style={[styles.bodySmall, { marginBottom: 20 }]}>
          {t.subtitle}
        </Text>

        {/* Badges infos */}
        <View style={[styles.row, { gap: 8, marginBottom: 20 }]}>
          <View style={styles.badge}>
            <Text style={{ color: "white", fontSize: 9 }}>{difficulty}</Text>
          </View>
          <View style={styles.badgeOutline}>
            <Text style={{ fontSize: 9 }}>{estimatedTime}</Text>
          </View>
          <View style={styles.badgeOutline}>
            <Text style={{ fontSize: 9 }}>{t.sizeLabel} {size}</Text>
          </View>
        </View>

        {/* Message de bienvenue */}
        <View
          style={[
            styles.card,
            { backgroundColor: "#F5F2ED", padding: 16, marginTop: 8 },
          ]}
        >
          <Text style={[styles.body, { fontStyle: "italic", lineHeight: 1.7 }]}>
            &quot;{t.welcome}&quot;
          </Text>
          <Text
            style={[styles.bodySmall, { marginTop: 8, textAlign: "right" }]}
          >
            — {t.team}
          </Text>
        </View>
      </View>

      {/* Footer */}
      <View
        style={{
          position: "absolute",
          bottom: 20,
          left: 40,
          right: 40,
          flexDirection: "row",
          justifyContent: "space-between",
        }}
      >
        <Text style={styles.footerText}>la-maille.vercel.app</Text>
        <Text style={styles.footerText}>{t.createdOn} {createdAt}</Text>
      </View>
    </Page>
  );
}
