import type { Language } from "./detect";

/**
 * Chaînes serveur pour la page patron publique (/patron/p/[slug]).
 * Volontairement hors de lib/i18n.ts : ce dernier est un module "use client"
 * (useTranslation) et ne peut pas être importé par un Server Component.
 * Même convention que lib/i18n/metadata.ts.
 */

export interface PublicPatternStrings {
  ctaTitle: string;
  ctaSubtitle: string;
  ctaButton: string;
  characteristics: string;
  type: string;
  construction: string;
  neckline: string;
  sleeves: string;
  stitch: string;
  fit: string;
  gauge: string;
  gaugeUnit: string;
  needles: string;
  yarn: string;
  estimatedYardage: string;
  instructions: string;
  castOn: string;
  castOnUnit: string;
  totalRows: string;
  rows: string;
  rowSingle: string;
  assembly: string;
  finishing: string;
  aboutTitle: string;
  aboutText: string;
  titlePrefix: string;
  descriptionTemplate: string;
  ogTagline: string;
  jsonLdDescription: string;
}

export const publicPatternStrings: Record<Language, PublicPatternStrings> = {
  fr: {
    ctaTitle: "Créez votre patron depuis une photo",
    ctaSubtitle:
      "Ce patron a été généré par La Maille à partir d'une simple photo. Uploadez la vôtre et obtenez un patron sur-mesure, gratuitement.",
    ctaButton: "Créez votre patron depuis une photo",
    characteristics: "Caractéristiques",
    type: "Type de vêtement",
    construction: "Construction",
    neckline: "Encolure",
    sleeves: "Manches",
    stitch: "Point principal",
    fit: "Coupe",
    gauge: "Échantillon",
    gaugeUnit: "m x {rows} rangs / 10 cm",
    needles: "Aiguilles",
    yarn: "Fil",
    estimatedYardage: "Quantité estimée",
    instructions: "Instructions du patron",
    castOn: "Montage",
    castOnUnit: "mailles",
    totalRows: "Total",
    rows: "Rangs",
    rowSingle: "Rang",
    assembly: "Assemblage",
    finishing: "Finitions",
    aboutTitle: "À propos de ce patron",
    aboutText:
      "Ce patron a été généré automatiquement par La Maille à partir de l'analyse d'une photo. Il constitue une base de travail : faites toujours un échantillon et ajustez selon votre fil et vos préférences.",
    titlePrefix: "Patron de tricot : ",
    descriptionTemplate:
      "Patron de tricot généré depuis une photo : {desc}. Échantillon {sts} m x {rows} rangs / 10 cm, aiguilles {needle} mm. Instructions rang par rang gratuites.",
    ogTagline: "Patron de tricot généré depuis une photo",
    jsonLdDescription:
      "Patron de tricot avec instructions rang par rang, généré depuis une photo par La Maille.",
  },
  en: {
    ctaTitle: "Create your pattern from a photo",
    ctaSubtitle:
      "This pattern was generated by La Maille from a single photo. Upload yours and get a made-to-measure pattern, for free.",
    ctaButton: "Create your pattern from a photo",
    characteristics: "Characteristics",
    type: "Garment type",
    construction: "Construction",
    neckline: "Neckline",
    sleeves: "Sleeves",
    stitch: "Main stitch",
    fit: "Fit",
    gauge: "Gauge",
    gaugeUnit: "sts x {rows} rows / 10 cm",
    needles: "Needles",
    yarn: "Yarn",
    estimatedYardage: "Estimated amount",
    instructions: "Pattern instructions",
    castOn: "Cast on",
    castOnUnit: "stitches",
    totalRows: "Total",
    rows: "Rows",
    rowSingle: "Row",
    assembly: "Assembly",
    finishing: "Finishing",
    aboutTitle: "About this pattern",
    aboutText:
      "This pattern was automatically generated by La Maille from a photo analysis. It is a working base: always knit a swatch and adjust to your yarn and preferences.",
    titlePrefix: "",
    descriptionTemplate:
      "Knitting pattern generated from a photo: {desc}. Gauge {sts} sts x {rows} rows / 10 cm, {needle} mm needles. Free row-by-row instructions.",
    ogTagline: "Knitting pattern generated from a photo",
    jsonLdDescription:
      "Knitting pattern with row-by-row instructions, generated from a photo by La Maille.",
  },
};

/** Labels d'enums d'analyse, par langue (sous-ensemble utile a la page publique). */
export const publicGarmentLabels: Record<Language, Record<string, string>> = {
  fr: {
    pull: "pull",
    cardigan: "cardigan",
    gilet: "gilet",
    autre: "tricot",
    unknown: "tricot",
  },
  en: {
    pull: "sweater",
    cardigan: "cardigan",
    gilet: "vest",
    autre: "knit",
    unknown: "knit",
  },
};

export const publicConstructionLabels: Record<Language, Record<string, string>> = {
  fr: {
    "pieces-assemblees": "pièces assemblées",
    "top-down": "top-down",
    "bottom-up": "bottom-up",
    "side-to-side": "côté à côté",
    unknown: "non identifiée",
  },
  en: {
    "pieces-assemblees": "seamed pieces",
    "top-down": "top-down",
    "bottom-up": "bottom-up",
    "side-to-side": "side to side",
    unknown: "unknown",
  },
};

export const publicNecklineLabels: Record<Language, Record<string, string>> = {
  fr: {
    "ras-du-cou": "col rond",
    "col-v": "col V",
    bateau: "encolure bateau",
    "ouvert-cardigan": "ouvert",
    capuche: "à capuche",
    unknown: "non identifiée",
  },
  en: {
    "ras-du-cou": "crew neck",
    "col-v": "V-neck",
    bateau: "boat neck",
    "ouvert-cardigan": "open front",
    capuche: "hooded",
    unknown: "unknown",
  },
};

export const publicSleeveLabels: Record<Language, Record<string, string>> = {
  fr: {
    montees: "manches montées",
    raglan: "raglan",
    marteau: "manches marteau",
    "sans-manches": "sans manches",
    unknown: "non identifiées",
  },
  en: {
    montees: "set-in sleeves",
    raglan: "raglan",
    marteau: "saddle shoulder",
    "sans-manches": "sleeveless",
    unknown: "unknown",
  },
};

export const publicStitchLabels: Record<Language, Record<string, string>> = {
  fr: {
    jersey: "jersey",
    mousse: "point mousse",
    cotes: "côtes",
    torsades: "torsades",
    jacquard: "jacquard",
    dentelle: "dentelle",
    autre: "autre",
    unknown: "non identifié",
  },
  en: {
    jersey: "stockinette",
    mousse: "garter stitch",
    cotes: "ribbing",
    torsades: "cables",
    jacquard: "colorwork",
    dentelle: "lace",
    autre: "other",
    unknown: "unknown",
  },
};

export const publicFitLabels: Record<Language, Record<string, string>> = {
  fr: {
    ajuste: "ajustée",
    regular: "regular",
    oversized: "oversized",
    unknown: "non identifiée",
  },
  en: {
    ajuste: "fitted",
    regular: "regular",
    oversized: "oversized",
    unknown: "unknown",
  },
};

export const publicYarnLabels: Record<Language, Record<string, string>> = {
  fr: {
    lace: "lace (dentelle)",
    fingering: "fingering",
    sport: "sport",
    dk: "DK",
    worsted: "worsted",
    aran: "aran",
    bulky: "bulky (grosse maille)",
  },
  en: {
    lace: "lace",
    fingering: "fingering",
    sport: "sport",
    dk: "DK",
    worsted: "worsted",
    aran: "aran",
    bulky: "bulky",
  },
};
